config/routes.rb
Rails.application.routes.draw do

  #Static Pages
  root 'static_pages#home'

  get '/about', to: 'static_pages#about'

  get '/help', to: 'static_pages#help'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'products/new'
  get '/products/:id', to: 'products#show'
  get '/products', to: 'products#index'


  get '/signup', to: 'users#new'
  get '/users', to: 'users#index'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

# Route for testing
  post '/reviews', to: 'reviews#create'

  #RESTFUL routes
  resources :products, :users

  resources :products do
      resources :reviews
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy  
end

app/models/review.rb
class Review < ApplicationRecord

  belongs_to :product
  validates :product_id, presence: true

  #listing 13.8
  belongs_to :user
  validates :user_id, presence: true

  default_scope -> { order(created_at: :desc)}

  validates :comment, presence: true, length: { maximum: 500 }
  validates :rating, presence: true, length: { maximum: 200 }



end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews, dependent: :destroy  

    before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    #confirms a logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = 'Please log in.'
        redirect_to login_url
      end
    end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    # @review = current_user.reviews.build if logged_in?
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(permitted_product_params)
    respond_to do |format|
      if @product.save
        flash[:success] = 'Product was successfully created.'
        format.html { redirect_to @product}
      else
        format.html {render :new}
      end
    end
  end

  def show
    @product = Product.find(params[:id])
  end

  def destroy
    @product = Product.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.'}
      format.json { head :no_content }
    end
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update #responds to patch request
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes!(permitted_product_params)
        flash[:success] = 'Product was successfully updated.'
        format.html { redirect_to product_path }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
        puts @product.errors.messages.inspect
      end
    end
  end



private

  def permitted_product_params
    params.require(:product).permit(:name, :price, :category, :product_id)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]

  def new
    @review = Review.new
    @product = Product.find(params[:product_id])
  end

  def show
  end

  def create
    @product = Product.find(params[:product_id])
    puts params[:product_id]

    # @review = Review.new(review_params)
    @review = current_user.reviews.build(review_params)
    if @review.save!
      flash[:success] = 'Review created!'
      redirect_to @product
    else
      redirect_to products_url
    end
  end

  def destroy
    @review = Review.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to @product, notice: 'Review was successfully destoyed.' }
      format.json { head :no_content }
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating, :product_id)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create # action - corresponds to POST
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in(user)
      redirect_to user
      #do something
    else
      #error message
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(permitted_user_params)
    respond_to do |format|
      if @user.save
        log_in(@user)
        flash[:success]= 'User was successfully created.'
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id]).destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destoyed.' }
      format.json { head :no_content }
    end
  end



private

  def permitted_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  #Logs in the given user
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Redmartrails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all','data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>

  <body>
    <%= render 'partials/header' %>
    <main class="container">
      <%= yield %>
    </main>
    <%= render 'partials/footer' %>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    by <a href="http://www.michaelhartl.com/">Michael Hartl</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '/about' %></li>
      <li><%= link_to "Help",   '/help' %></li>
    </ul>
  </nav>
</footer>

app/views/partials/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#mynavbar" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        <%= link_to "RedMart Rails", '/', id: "logo", class: "navbar-brand" %>
        </div>
        <nav class="collapse navbar-collapse" id="mynavbar">
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "About",   '/about' %></li>
            <% if logged_in? %>
              <li><%= link_to 'Profile', current_user %></li>
              <li><%= link_to 'Log out', '/logout', method: 'delete' %></li>
            <% else %>
              <li><%= link_to "Log In", '/login' %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/products/edit.html.erb
<h1>Products#edit</h1>

  <div class="field">
  <%= form_for @product do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :category %>
    <%= f.text_field :category %>

    <%= f.label :price %>
    <%= f.number_field :price %>

    <%= f.submit "Save changes"%>
  <% end %>
  </div>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="table">
  <thead>
    <th>#</th>
    <th>Product Name</th>
    <th>Product Category</th>
    <th>Product Price</th>
    <th class="center" colspan="3">Action</th>
  </thead>
  <tbody>
    <% @products.each do |product| %>
    <tr>
      <th scope="row"><%=product.id%></th>
      <td> <%= link_to product.name, product %> </td>
      <td> <%= product.category %> </td>
      <td> <%= product.price %> </td>
      <td> <%= link_to 'Review', new_product_review_path(product) %> </td>
      <td> <%= link_to 'Edit', edit_product_path(product) %> </td>
      <td> <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?'}%> </td>
    </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>Products#new</h1>
<p>Find me in app/views/products/new.html.erb</p>

<%= form_for(@product) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :category %>
  <%= f.text_field :category %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.submit "Create New Product" %>
<% end %>

app/views/products/show.html.erb
<div class="container">
  <p>
    <strong>Name:</strong>
    <%= @product.name %>
  </p>

  <p>
    <strong>category:</strong>
    <%= @product.category %>
  </p>

  <p>
    <strong>price:</strong>
    <%= @product.price %>
  </p>
</div>

<% if @product.reviews.any? %>
  <h3>Reviews (<%= @product.reviews.count %>)</h3>
  <table class="table">
  <thead>
    <tr>
      <th>Comment</th>
      <th>Rating</th>
      <th>User</th>
      <th class="center" colspan="3">Action</th>
    </tr>
  </thead>
  <%= render Review.all %>
</table>
<% end %>

app/views/reviews/_review.html.erb
  <tbody>
    <tr>
      <td> <%= review.comment %> </td>
      <td> <%= review.rating %> </td>
      <td> <%= review.user.name %> </td>
      <td> <%= link_to 'Review', '#' %> </td>
      <td> <%= link_to 'Edit', '#' %> </td>
      <td> <%= link_to 'Destroy', '#'%> </td>
    </tr>
  </tbody>

app/views/reviews/new.html.erb
<h1>Review#new</h1>

<%= form_for ([@product, @review]) do |f| %>


<%= f.hidden_field :product_id, :value => @product.id %>

  <%= f.label :comment %><br>
  <%= f.text_area :comment %><br>
  <br>
  <%= f.label :rating %><br>
  <%= f.text_area :rating %><br>
  <br>
  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<p>show one single review</p>

<% if @user.reviews.any? %>
  <h3>Reviews (<%= @user.reviews.count %>)</h3>
  <%= render @reviews %>
  <% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to 'Purchase Products', '/products', class: "btn btn-lg btn-primary" %>
</div>

app/views/users/index.html.erb
<h1>Users</h1>

<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>Name</th>
      <th>Email</th>
      <th></th>
      <th>Actions</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
    <tr>
      <th scope="row"><%= user.id %></th>
      <td> <%= user.name %> </td>
      <td> <%= user.email %> </td>
      <td> <%= link_to 'Show', user %> </td>
      <td> <%= link_to 'Edit', edit_user_path(user) %> </td>
      <td> <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?'}%> </td>
    </tr>
    <% end %>
  </tbody>

</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for(@user) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password%>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Password Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>